### ISSUE TITLE
Firefox shows blurry image after transition

### ISSUE THREAD

**Issue by 00sapo** [sozi-projects/Sozi#464] opened 2019-10-23 16:00 UTC
Firefox shows good resolution only after reloading. After a transition the image remains blurry.
I'm using Sozi 19 and Inkscape 0.92.4 on Manjaro Linux.

The attached zip contains a simple example.

[ismir_slides.zip](https://github.com/senshu/Sozi/files/3763298/ismir_slides.zip)

**Comment by senshu** [comment] 2019-10-23 16:59
As far as I can see, this problem happens only with Firefox. In Chrome, I have no blurry images.
I'll see what I can do.

**Comment by Moini** [comment] 2019-10-23 17:11
Zooming in and out helps to fix this, too...

**Comment by senshu** [comment] 2019-11-07 22:02
I have pushed a modification that seems to solve the issue for me (to be honest, after staring at the same document for some time, reloading and zooming repeatedly, everything seems blurry to me now).

The solution is a hack that I found in this thread : https://stackoverflow.com/questions/15464055/css-transition-effect-makes-image-blurry-moves-image-1px-in-chrome

I will upload a new version of Sozi for testers soon. You will be able to try it.

**Comment by m4chi** [comment] 2021-04-12 00:17
Hi, I have a similar issue with Firefox, Ubuntu 20.04, Sozi 21.02.21. When I load the svg in Sozi, all images show properly. The Presenter View also shows clear images, but displaying the presentation in a window (presenter view) or loading the .html (no presenter view) results in very blurry images. Strangely, when i switch Firefox tabs and switch back, the images are suddenly clear, but as soon as I move to the next frame, they are blurry again. Chromium does not have this issue. Sorry for the bother.

**Comment by aumouvantsillage** [comment] 2021-12-01 22:34
I have spent several hours trying to find a workaround for this issue, without any success.
I guess we'll have to wait until the issue is fixed in Firefox.

It's sad because Firefox used to be my preferred browser for playing Sozi presentations.
Now the recommended browsers are those based on Chromium (Chrome, Edge, Vivaldi, etc.)

**Comment by aumouvantsillage** [comment] 2024-11-17 20:46
Closing this issue. I could not reproduce the problem in Firefox 132, so I assume it is fixed.

**Closed by aumouvantsillage** 2024-11-17 20:46 UTC
Labels: Player, bug, in progress, Help needed
