### ISSUE TITLE
Layer disappears when re-loading SVG

### ISSUE THREAD

**Issue by AlexiaMt** [sozi-projects/Sozi#503] opened 2021-01-17 11:34 UTC
Hi,

First of all thanks for developing this very nice software :)

### Summary of your problem or feature request

I'm trying to animate a graph using several layers, but one of the layers disappears every time I re-load the SVG file. The graph is placed in a rectangle which is used to create the frame in Sozi. The missing layer re-appears when I re-adjust the frame to the rectangle with the autoselect button (see 1st screenshot here attached). When I hover the mouse over the frame, a dashed rectangle appears around the frame. The layer disappears again once I re-load the SVG file (see 2nd screenshot) and when I hover the mouse over the frame, there are two dashed rectangles which seem to split the frame in two. I have made sure that the missing layer opacity is set to 1. This has happened several times and I haven't found how to get around it.

<img width="960" alt="screenshot-1" src="https://user-images.githubusercontent.com/49063975/104839076-379d8500-58bf-11eb-8975-1c7df262a6d4.png">
<img width="960" alt="screenshot-2" src="https://user-images.githubusercontent.com/49063975/104839081-3cfacf80-58bf-11eb-9227-1d33160c5b92.png">

### Version of Sozi and other relevant software

Sozi 20.05
Inkscape 1.0
Windows 10 64-bit

**Comment by aumouvantsillage** [comment] 2021-01-17 21:44
The dashed rectangles represent the clipping region.
Have you tried to disable clipping on the layer that disappears?

Can you provide an example presentation (SVG + JSON files) and a detailed, reproducible procedure to help me investigate the problem?

**Comment by aumouvantsillage** [comment] 2021-12-01 20:21
Closing due to lack of information.

**Closed by aumouvantsillage** 2021-12-01 20:21 UTC
Labels: bug, information-needed
